/**
 * vuex注册 mutations
 * */

/** user模块 */
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_SET_ROLES = 'USER_SET_ROLES'
export const USER_SET_NAME = 'USER_SET_NAME'

/** permission模块 */
export const PERMISSION_SET_ROUTES = 'PERMISSION_SET_ROUTES'
export const PER_SET_HAS_HANDLE_ROUTES = 'PER_SET_HAS_HANDLE_ROUTES'

/** app 模块 */
export const APP_TOGGLE_SIDEBAR = 'APP_TOGGLE_SIDEBAR'
export const APP_CLOSE_SIDEBAR = 'APP_CLOSE_SIDEBAR'

/** tagView模块 */
export const TAGS_VIEW_ADD_VISITED_VIEW = 'TAGS_VIEW_ADD_VISITED_VIEW'
export const TAGS_VIEW_ADD_CACHED_VIEW = 'TAGS_VIEW_ADD_CACHED_VIEW'
export const TAGS_VIEW_DEL_VISITED_VIEW = 'TAGS_VIEW_DEL_VISITED_VIEW'
export const TAGS_VIEW_DEL_CACHED_VIEW = 'TAGS_VIEW_DEL_CACHED_VIEW'
export const TAGS_VIEW_DEL_OTHERS_VISITED_VIEWS = 'TAGS_VIEW_DEL_OTHERS_VISITED_VIEWS'
export const TAGS_VIEW_DEL_OTHERS_CACHED_VIEWS = 'TAGS_VIEW_DEL_OTHERS_CACHED_VIEWS'
export const TAGS_VIEW_DEL_ALL_VISITED_VIEWS = 'TAGS_VIEW_DEL_ALL_VISITED_VIEWS'
export const TAGS_VIEW_DEL_ALL_VISITED_VIEWS_EXCE_FIX = 'TAGS_VIEW_DEL_ALL_VISITED_VIEWS_EXCE_FIX'
export const TAGS_VIEW_DEL_ALL_CACHED_VIEWS = 'TAGS_VIEW_DEL_ALL_CACHED_VIEWS'
export const TAGS_VIEW_UPDATE_VISITED_VIEW = 'TAGS_VIEW_UPDATE_VISITED_VIEW'
